### ISSUE TITLE
Tidy up test suite

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1252]
This is a deliberately vague issue - as was pointed out on #1251 it's not totally clear how to run the tests or add new ones, and there are probably a few different ways that can be improved. Some ideas:
- [ ] Use ES6 modules everywhere instead of AMD, since that's what the codebase uses
- [ ] Move tests out of misc.js and into their proper homes, where possible
- [ ] Better guidance about how to run tests and where to add new ones

There was some talk, long ago, about switching from QUnit to something else (probably Mocha). That would take a Herculean effort, possibly out of all proportion to any gains - though it would be good to investigate whether a test runner that used JSDOM instead of PhantomJS would make life easier. (I get nervous about relying on a 'synthetic DOM', but a lot of people seem to use it without issue.)

Another consideration: proper unit tests. At the moment the test suite is mostly concerned with testing the entire system, though there are a few unit/integration tests in there as well. I wonder whether it'd make more sense to have a stricter separation - we could e.g. use [Jest](http://facebook.github.io/jest/) for unit tests (it looks pretty great), and keep them in `__tests__` folders next to the modules they're testing, which would a) make it easier to be disciplined about adding/maintaining those tests, b) take pressure off the 'main' test suite (which becomes exclusively for system tests), and c) go some way towards documenting what the various modules do.
