### ISSUE TITLE
Improve build process

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1573]
Following #1485, there are a few tasks:

* [x] fixing https://github.com/Rich-Harris/esperanto/issues/15, since we can't use named imports/exports otherwise (results in conflicting variable names)
* [x] figuring out how to stop 6to5 from adding a 'use strict' directive to every file
* [x] getting sourcemaps up and running
* [x] rewriting or separating all the tests that test (or rely on) individual modules, or overwrite them. Having these unit/integration tests in the same suite as the end-to-end tests means having to create a bundle *and* all the one-to-one transpiled AMD modules
* [x] general tidy up of the gobblefile and grunt tasks
* [ ] add back `noConflict`

Once that's out of the way, there are a few things we can do to tidy up the source code itself, some of which will decrease file size (using Esperanto instead of RequireJS+AMDClean already reduces the minified filesize a bit, but there's more we can do)

**Comment by Rich-Harris** [comment]
Will close this issue as most stuff is now taken care of. `noConflict` has been removed since 0.6.1 because the new build process only registers Ractive as a global in the absence of a module system - both those things can be patched if it turns out people actually need them.

Still interested in using mocha everywhere, as it has some nice features, but I reckon that's a separate issue. In any case, there's currently a real dealbreaker in the form of https://github.com/mochajs/mocha/issues/553 - there's no equivalent of QUnit's notrycatch option, which means you get a useless non-interactive non-sourcemapped stack trace in the browser, rather than a proper one in the console.
